<template>
  <q-input
    v-bind="$props"
    inputmode="numeric"
    prefix="R$"
    mask="#.##"
    fill-mask="0"
    reverse-fill-mask
  >
    <template
      v-for="(_, slot) of $slots"
      #[slot]="scope"
    >
      <slot
        :name="slot"
        v-bind="scope"
      />
    </template>
  </q-input>
</template>
